### ISSUE TITLE
Update use of KPCC article API to V3

### ISSUE THREAD

**Issue by chrislkeller** [SCPR/firetracker#185]
* Can we take advantage of tags? Something like Firetracker - {{ fire_name }}

* Also: Why doesn’t this [story](http://www.scpr.org/news/2015/02/08/49720/containment-up-on-fire-that-destroyed-40-homes-in/) show up on the [Round Fire page](http://firetracker.scpr.org/round-fire/)?

**Comment by ewr** [comment]
Your second question got me curious... Here's the API search URL:

http://www.scpr.org/api/v2/content/?types=news,blogs,segments&query=Round+Fire+Inyo+and+Mono+County&limit=5&page=1

It's "County" that trips you up. The story title includes "Counties", but not "County."

I'm not 100% sure what we would need to do to enable stemming on that, but in the meantime you may want to look at tightening up the query. For instance:

http://www.scpr.org/api/v2/content/?types=news,blogs,segments&query=%22Round+Fire%22+Inyo+Mono&limit=5&page=1

Would search for "Round Fire" as a phrase, not just Round and Fire in the content.
