### ISSUE TITLE
Allow external partners to add fire images

### ISSUE THREAD

**Issue by frankreporting** [SCPR/firetracker#200]
Currently we use a KPCC Asset Host ID for all our fires, which makes it impossible for outside partners to add an image to a fire they're tracking closely - at least without assistance. Is there a way to add outside image links to Fire Tracker or, alternately, give them limited access to Asset Host for this purpose? Not sure which is easier, but for security reasons it probably makes more sense to handle it within Fire Tracker and not get the Asset Host involved.

**Comment by chrislkeller** [comment]
As far as adding capability to use CPR images into the system, I should be able to do this pretty quick.

I'm thinking you'd need to provide the ID and name of the image that is generated by your system.

For example: 5047424/0816-bear-fire-p.jpg would point to this image

http://www.capradio.org/umbraco/ImageGen.ashx?image=/media/5047424/0816-bear-fire-p.jpg&width=1000

I would handle the URL prefix and the width in the code
