### ISSUE TITLE
Name collisions happen with slugs

### ISSUE THREAD

**Issue by Ravenstine** [SCPR/firetracker#214]
It seems like there are some points of conflict in terms of what slug is used as an id.

This seems to suggest that a created_fire_id with the correct slug format is created on-save:
https://github.com/SCPR/firetracker/blob/b2269f72fce1de7cccf235122500cb93d11e1c9d/calfire_tracker/models.py#L147-L194

Yet the code that returns a permalink uses ‘fire_slug’:
https://github.com/SCPR/firetracker/blob/b2269f72fce1de7cccf235122500cb93d11e1c9d/calfire_tracker/models.py#L131-L133

Which is this:
https://github.com/SCPR/firetracker/blob/b2269f72fce1de7cccf235122500cb93d11e1c9d/calfire_tracker/data_manager.py#L617

For example, when a recent fire called "Park Fire" was added, it got the same slug as a previous fire with the same name, causing a server error when 2 fires get returned at once for a show page.

- [ ] - AC: Name collisions with slugs don't happen in this way.

**Comment by chrislkeller** [comment]
@Ravenstine: Pardon the chiming in... :)

Ultimately they should really have been one and the same...

```created_fire_id``` is used to differentiate and make the distinction between fires. It's used as a lookup key when a new fire is found when scraping.

```fire_slug``` is the basis for the URL at which the fire is returned.

Really, they could be one and the same, and be something the lines of ```"%s-%s-%s" % (fire_name, county, year)```...

**Comment by Ravenstine** [comment]
☝️ see dat
